CREATE TABLE "public".feedback (
    feedback_id bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_name varchar(30) NOT NULL,
    user_role varchar(30) NOT NULL,
    user_company varchar(30) NOT NULL,
    user_feedback varchar(500) NOT NULL
);

CREATE UNIQUE INDEX feedback_id_index on "public".feedback (feedback_id);
